SCCapstone/DKMS

README.md, app/page.tsx
=> feat: prepare for Vercel OSS sponsorship application

.vscode/settings.json, app/globals.css, app/layout.tsx, app/page.tsx, package.json, tailwind.config.js, yarn.lock
=> chore: re-install DaisyUI + Tailwind

app/layout.tsx, components/sidebar/SidebarContainter.tsx, components/sidebar/icons/FriendsIcon.tsx, components/sidebar/icons/NotificationIcon.tsx, components/sidebar/icons/PlaybackIcon.tsx
Allows for #22 (#82) development to continue.
=> feat: create right sidebar component

app/profile/page.tsx
- fix: changed user.id to user.name to correctly filter database for a profile
=> fix: profile filtering issue

app/profile/[[...username]]/page.tsx
- feat: added optional catch-all parameter to profile url 
- feat: if parameter is provided, will navigate to filtered profile page of given username
- feat: if no parameter is provided, will navigate to profile page of currently logged in user
=> feat: added functional url parameters for profile

app/(feed)/page.tsx, app/profile/[[...username]]/page.tsx, components/feed/FeedItem.tsx, components/feed/FeedPage.tsx, components/sidebar/Friends.tsx, components/sidebar/Notifications.tsx, components/ui/UsernameLink.tsx
- refactor: simplify user fetch code
- feat: reorganize feed page
- feat: add clickable links to feed page
- fix: add key to list of friends + notifications
- feat: add profile links to sidebar components
=> feat: make usernames clickable

.eslintrc.json, .gitignore, cypress.config.ts, cypress/support/e2e.ts, package.json, postcss.config.js, yarn.lock
- feat: install ESLint Cypress plugin
- feat: write basic E2E test
- chore: confure Cypress settings
- chore: link to Cypress Cloud
=> chore: update Cypress configs

app/profile/[[...username]]/page.tsx, app/search/SearchResults.tsx, app/search/page.tsx, app/session/SessionInfo.tsx, lib/firestore/index.ts, lib/firestore/types.ts, package.json, pages/api/auth/[...nextauth].ts, types/next-auth.d.ts, yarn.lock
- chore: install firebase adapter
- feat: standardize user information stored in firestore
=> feat: add next-auth firestore adapter

lib/firestore/index.ts, lib/firestore/types.ts, pages/api/auth/[...nextauth].ts
- feat: store top track and artist IDs
- feat: store entire artist and song data on firebase
=> feat: store profile page data in Firestore

app/layout.tsx, components/Sidebar/DesktopSidebar.tsx, components/Sidebar/MobileSidebar.tsx, components/Sidebar/index.tsx, components/Sidebar/panels/BasePanel.tsx, components/Sidebar/panels/Friends.tsx, components/Sidebar/panels/Notifications.tsx, components/Sidebar/panels/index.tsx
This allows for data fetchiing inside a panel
=> feat: move sidebar panels to server-side

lib/followers/getUsersFollowing.ts, lib/followers/isUserFollowing.ts
- refactor: make isUserFollowing take in multiple users
- feat: create getUsersFollowing lib function
=> Refactor following lib functions

app/(music)/album/[id]/AlbumView.tsx, app/(music)/album/[id]/page.tsx, app/(music)/artist/[id]/ArtistView.tsx, app/(music)/artist/[id]/page.tsx, app/(music)/playlist/[id]/PlaylistView.tsx, app/(music)/playlist/[id]/page.tsx, app/(music)/track/[id]/TrackView.tsx, app/profile/[username]/page.tsx, components/music/AudioFeatures.tsx, lib/getAverageAudioFeatures.ts
- fix: add view album button
- feat: show average audio features for an album
- feat: add average statistics to artist page
- feat: add audio features to playlist
- feat: make audio features a stats component
- feat: add audio features to profile page
=> feat: add additional audio analysis

app/profile/[username]/page.tsx, app/recommendations/page.tsx, lib/recommendations/getRecommendationsForUser.ts, lib/recommendations/getRecommendedArtists.ts
Displays recommended artists on recommendations page.
=> 279 add recommended artists to recommendations page

app/(music)/artist/[id]/ArtistView.tsx, app/(music)/artist/[id]/page.tsx
Displays similar artists on the artist page
=> 280 add similar artists to artist page

app/profile/[username]/page.tsx, components/music/grids/PlaylistsGrid.tsx, lib/getPlaylistsForUser.ts
- feat: see user's playlist on profile page
- feat: maximum of 8 profiles
=> feat: see user's playlists

app/recommendations/page.tsx, components/RecommendationFilterButtons.tsx, lib/recommendations/getRecommendationsBySeed.ts, lib/recommendations/getRecommendationsForUser.ts, lib/recommendations/recommendationTargets.ts
- feat: allow for a target recommendation
- feat: add recommendation buttons
=> feat: filter recommendations

app/profile/[username]/page.tsx, components/ui/ArtistLinks.test.tsx, cypress/e2e/navigation.spec.ts, cypress/fixtures/user-development.json, cypress/support/commands.ts, cypress/support/component.ts, lib/formatters.test.ts, lib/recommendations/getRecommendationsForUser.ts, lib/recommendations/getRecommendedArtists.ts
- test: fix formatters tests
- test: fix artist links test
- chore: add tailwind CSS to cypress component testing
- feat: show warning when user does not have profile data
- fix: create seperate dev and prod fixtures
- test: test all navbar clicks
- fix: return default artist data for recommendations when no topArtists exist
=> test: fix tests + misc errors

components/feed/FeedItem.tsx, components/feed/FeedItemComment.tsx, components/feed/index.tsx
- fix: reconfigured order of lines to get rid of extra lines
=> Got rid of extra lines

app/(marketing)/MarketingNavbar.tsx, app/(marketing)/auth/signin/SignInButton.tsx, app/(marketing)/auth/signin/page.tsx, app/(marketing)/layout.tsx, lib/fetch/baseFetch.ts, middleware.ts, pages/api/auth/[...nextauth].ts
- fix: simplify middleware
- feat: create basic sign in page
- feat: create marketing page layout
- feat: style sign in page
- fix: redirect to sign in when not authorized
- refactor: explain more clearly sign in errors
- fix: go to home page on menu bar click
=> feat: add sign in page with errors

app/app/search/SearchMenu.tsx
Added character limit to search
=> feat: search char limit

components/feed/FeedCommentBox.tsx, components/feed/FeedItem.tsx, components/feed/FeedItemComment.tsx, components/feed/FeedTextBox.tsx
Added character limit to comments
Added character limit to posts
=> 359 large comments dont load add char limit

app/(marketing)/route.tsx, app/app/profile/route.tsx, cypress/e2e/login.spec.ts, cypress/e2e/navigation.spec.ts, cypress/fixtures/user-development.json, cypress/support/commands.ts, package.json, yarn.lock
- fix: fix routing in production environment
- chore: update cypress
=> fix: fix tests

app/(marketing)/layout.tsx
- fix: remove borders of marketing page (forgot to revert commit)
=> fix: removed borders

cypress/e2e/search.spec.ts
- test: write tests for search page
- test: add tests for search navigating to new page
=> test: test search page

app/(marketing)/auth/signout/SignOutButton.tsx, app/(marketing)/auth/signout/page.tsx, next.config.js, pages/api/auth/[...nextauth].ts
- feat: create sign out page
- feat: add manual redirects for login
=> feat: create sign out page

components/Sidebar/panels/Queue/index.tsx, lib/playback/getQueue.ts
=> fix: null item in queue from podcast

components/Player/index.tsx
- feat: add instructions for playback
=> feat: add playback setup instructions
